// MIT License
// Copyright (c) 2024-2026 Ronan Le Meillat - SCTG Development

/**
 * Adapter for Mistral's native /v1/conversations endpoint.
 *
 * The conversations API differs from /v1/chat/completions in three ways:
 *  - Body shape: { inputs, tools, completion_args, instructions } instead of
 *    { messages, temperature, … }
 *  - Built-in tools (image_generation) can produce image outputs natively.
 *  - Response shape: { outputs: [ { type: 'tool.execution'|'message.output', … } ] }
 *    where image URLs are nested inside outputs[].info.result (a JSON string).
 */

import type { AiProvider } from '../../types/ai-config';
import type { PlaygroundImagePart, PlaygroundMessage, PlaygroundPart } from '../../types/playground-types';

// ---------------------------------------------------------------------------
// URL builder
// ---------------------------------------------------------------------------

/** Derives the /v1/conversations URL from the provider's endpoint. */
export function buildMistralConversationsUrl(provider: AiProvider): string {
  const base = provider.endpoint
    .replace(/\/+$/, '')
    .replace(/\/chat\/completions$/, '')
    .replace(/\/models$/, '');
  return `${base}/conversations`;
}

// ---------------------------------------------------------------------------
// Payload builder
// ---------------------------------------------------------------------------

export interface MistralConversationsPayloadOptions {
  modelId: string;
  systemPrompt: string;
  messages: PlaygroundMessage[];
  temperature: number;
  maxTokens: number;
  topP: number;
}

/** Converts a PlaygroundPart to plain text for the conversations inputs array. */
function partToText(part: PlaygroundPart): string | null {
  if (part.type === 'text') return part.text;
  if (part.type === 'audio' && part.transcription) return part.transcription;
  if (part.type === 'file' && part.textContent) return part.textContent;
  return null;
}

/**
 * Builds the request body for POST /v1/conversations.
 * Images generated by previous turns are skipped (they live server-side
 * and cannot be re-uploaded to the stateless inputs array).
 */
export function buildMistralConversationsPayload(
  options: MistralConversationsPayloadOptions,
): unknown {
  const { modelId, systemPrompt, messages, temperature, maxTokens, topP } = options;

  const inputs = messages
    .map((msg) => {
      const text = msg.parts
        .map(partToText)
        .filter((t): t is string => t !== null)
        .join('\n\n')
        .trim();
      if (!text) return null;
      return { role: msg.role, content: text };
    })
    .filter((m): m is NonNullable<typeof m> => m !== null);

  return {
    model: modelId,
    inputs,
    tools: [{ type: 'image_generation' }],
    completion_args: {
      temperature,
      max_tokens: maxTokens,
      top_p: topP,
    },
    ...(systemPrompt.trim() ? { instructions: systemPrompt.trim() } : {}),
  };
}

// ---------------------------------------------------------------------------
// Response parser
// ---------------------------------------------------------------------------

type JsonRecord = Record<string, unknown>;

/**
 * Parses a /v1/conversations response body into playground parts.
 *
 * Strategy:
 *  1. Scan outputs[] for tool.execution entries whose info.result JSON holds
 *     the generated image URL.
 *  2. Scan outputs[] for message.output entries to extract text and tool_file
 *     items, substituting the collected URL for each tool_file placeholder.
 */
export function extractMistralConversationsParts(body: unknown): PlaygroundPart[] {
  if (typeof body !== 'object' || body === null) {
    return [{ type: 'text', text: 'No response.' }];
  }

  const outputs = (body as JsonRecord)['outputs'];
  if (!Array.isArray(outputs)) return [{ type: 'text', text: 'No response.' }];

  // Pass 1 — collect image URLs from tool executions (in order of appearance).
  const imageUrls: string[] = [];
  for (const raw of outputs) {
    if (typeof raw !== 'object' || raw === null) continue;
    const entry = raw as JsonRecord;
    if (entry['type'] !== 'tool.execution' || entry['name'] !== 'image_generation') continue;
    const info = entry['info'];
    if (typeof info !== 'object' || info === null) continue;
    const result = (info as JsonRecord)['result'];
    if (typeof result !== 'string') continue;
    try {
      const parsed = JSON.parse(result) as JsonRecord;
      if (typeof parsed['url'] === 'string') imageUrls.push(parsed['url']);
    } catch { /* malformed JSON inside result — skip */ }
  }

  // Pass 2 — build parts from message.output entries.
  const parts: PlaygroundPart[] = [];
  let imageIndex = 0;

  for (const raw of outputs) {
    if (typeof raw !== 'object' || raw === null) continue;
    const entry = raw as JsonRecord;
    if (entry['type'] !== 'message.output') continue;
    const content = entry['content'];
    if (!Array.isArray(content)) continue;

    for (const rawItem of content) {
      if (typeof rawItem !== 'object' || rawItem === null) continue;
      const item = rawItem as JsonRecord;

      if (item['type'] === 'text' && typeof item['text'] === 'string') {
        const trimmed = (item['text'] as string).trim();
        if (trimmed) parts.push({ type: 'text', text: item['text'] as string });
        continue;
      }

      if (item['type'] === 'tool_file' && item['tool'] === 'image_generation') {
        const url = imageUrls[imageIndex++];
        if (!url) continue;
        const fileName =
          typeof item['file_name'] === 'string'
            ? `${item['file_name']}.${item['file_type'] ?? 'png'}`
            : 'generated_image.png';
        const imagePart: PlaygroundImagePart = {
          type: 'image',
          remoteUrl: url,
          name: fileName,
        };
        parts.push(imagePart);
      }
    }
  }

  return parts.length > 0 ? parts : [{ type: 'text', text: 'No response.' }];
}
