// MIT License
// Copyright (c) 2024-2026 Ronan Le Meillat - SCTG Development
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

/**
 * Multimodal playground types.
 * Supports text, image, audio, video, file, code, and TTS output parts.
 */

/** Role of a participant in a playground conversation. */
export type PlaygroundRole = 'user' | 'assistant';

/** Base64-encoded binary data for inline image, audio, or video parts. */
export interface PlaygroundInlineData {
  /** MIME type of the embedded data (e.g. `"image/png"`). */
  mimeType: string;
  /** Base64-encoded file content (without the data-URL prefix). */
  data: string;
}

/** A text part in a playground message. */
export interface PlaygroundTextPart {
  type: 'text';
  /** The text content of the part. */
  text: string;
}

/** An image part in a playground message, either inline or remote. */
export interface PlaygroundImagePart {
  type: 'image';
  /** Base64-encoded image. Present for user-uploaded images. */
  inlineData?: PlaygroundInlineData;
  /** Remote URL for API-generated images (e.g. Mistral image_generation tool). */
  remoteUrl?: string;
  /** Optional display name for the image. */
  name?: string;
  /** Optional file size in bytes. */
  size?: number;
  /** Object URL for thumbnail display — must be revoked on unmount. */
  thumbnailUrl?: string;
}

/** An audio part in a playground message (input audio with optional transcription). */
export interface PlaygroundAudioPart {
  type: 'audio';
  /** Base64-encoded audio data. */
  inlineData: PlaygroundInlineData;
  /** Optional display name for the audio file. */
  name?: string;
  /** Optional file size in bytes. */
  size?: number;
  /** Text produced by an optional speech-to-text pass. */
  transcription?: string;
}

/** A video part in a playground message. */
export interface PlaygroundVideoPart {
  type: 'video';
  /** Base64-encoded video data. */
  inlineData: PlaygroundInlineData;
  /** Optional display name for the video file. */
  name?: string;
  /** Optional file size in bytes. */
  size?: number;
  /** Object URL for thumbnail display — must be revoked on unmount. */
  thumbnailUrl?: string;
}

/** A generic file part in a playground message. */
export interface PlaygroundFilePart {
  type: 'file';
  /** Base64-encoded file data. */
  inlineData: PlaygroundInlineData;
  /** The filename of the uploaded file. */
  name: string;
  /** Optional file size in bytes. */
  size?: number;
  /** Decoded text content for providers that receive files as inline text. */
  textContent?: string;
}

/** A code block part in a playground message. */
export interface PlaygroundCodePart {
  type: 'code';
  /** The programming language identifier (e.g. `"python"`). */
  language: string;
  /** The source code content. */
  code: string;
  /** Optional filename associated with the code. */
  filename?: string;
}

/** Audio produced by a text-to-speech model, either inline or remote. */
export interface PlaygroundTtsAudioPart {
  type: 'tts_audio';
  /** Base64-encoded audio generated by the model. */
  inlineData?: PlaygroundInlineData;
  /** Remote URL when the provider returns a hosted audio asset. */
  audioUrl?: string;
  /** MIME type of the audio (e.g. `"audio/wav"`). */
  mimeType?: string;
  /** Optional filename for the audio file. */
  filename?: string;
  /** Optional transcript returned alongside the model-generated audio. */
  transcript?: string;
}

/** Union of all possible part types that can appear in a playground message. */
export type PlaygroundPart =
  | PlaygroundTextPart
  | PlaygroundImagePart
  | PlaygroundAudioPart
  | PlaygroundVideoPart
  | PlaygroundFilePart
  | PlaygroundCodePart
  | PlaygroundTtsAudioPart;

/** A single message within a playground conversation. */
export interface PlaygroundMessage {
  /** Unique identifier for the message (UUID). */
  id: string;
  /** Role of the message author. */
  role: PlaygroundRole;
  /** Ordered list of content parts contained in this message. */
  parts: PlaygroundPart[];
  /** Epoch timestamp (ms) marking when the message was created. */
  timestamp: number;
}

/** Container for a sequence of messages exchanged with a model. */
export interface PlaygroundConversation {
  /** Unique identifier for the conversation. */
  id: string;
  /** Human-readable title shown in the history sidebar. */
  title: string;
  /** Ordered list of messages in this conversation. */
  messages: PlaygroundMessage[];
  /** Epoch timestamp (ms) marking when the conversation was created. */
  createdAt: number;
  /** Epoch timestamp (ms) marking when the conversation was last updated. */
  updatedAt: number;
}

/**
 * Injected speech-to-text service. The playground calls this for audio parts
 * before sending the message — keeps provider keys server-side.
 *
 * @param audio - The raw audio Blob from the file input.
 * @param file - The original File object (may carry a name/extension hint).
 * @returns The transcribed text content.
 */
export type PlaygroundTranscriber = (audio: Blob, file: File) => Promise<string>;

/** Result of a text-to-speech provider call. */
export interface PlaygroundTtsResult {
  /** Inline audio blob when the provider returns binary audio data. */
  audioBlob?: Blob;
  /** Remote URL when the provider hosts the audio at a separate endpoint. */
  audioUrl?: string;
  /** MIME type of the audio data. */
  mimeType?: string;
}

/**
 * @deprecated Assistant audio playback must come from model-generated `tts_audio`
 * parts, not from a client-side or injected text-to-speech function.
 */
export type PlaygroundTtsProvider = (text: string) => Promise<PlaygroundTtsResult>;

// ---------------------------------------------------------------------------
// Legacy types — kept for backward compatibility with existing code that still
// imports PlaygroundFile / PlaygroundMessage (old shape). The playground panel
// now uses the new PlaygroundMessage shape above.
// ---------------------------------------------------------------------------

/** @deprecated Use PlaygroundFilePart instead. */
export interface PlaygroundFile {
  /** Unique file identifier. */
  id: string;
  /** Human-readable filename. */
  name: string;
  /** MIME type of the file. */
  type: string;
  /** File size in bytes. */
  size: number;
  /** Base64-encoded file content. */
  content: string;
}
